### ISSUE TITLE
Add `Protobuf` files for Okane

### ISSUE THREAD

**Issue by NikhilSharma03** [NikhilSharma03/Okane#1]
## Description

- Add `Protobuf` files for Okane

**Comment by jinwoo1225** [comment]
wow 😲 what this project does? Just interested 🤩

**Comment by NikhilSharma03** [comment]
Yoo @jinwoo1225. How are you doing? ✋

This project is an advance version of the previous project (https://github.com/NikhilSharma03/ExpenseTracker).
The main idea is to add new features and follow good project structure principles while developing the app.

**Comment by jinwoo1225** [comment]
Long time no see 🤙 .. I get busy at work..

great work you did on ExpenseTracker! you got fully turned into gopher? 

in that case, I might wanna contribute to this project! (I almost forgot how to code in TypeScript 🤣 )

**Comment by NikhilSharma03** [comment]
In my case it's vice versa 🤣, I have been writing TypeScript, Rust, and Blockchain for the past 2 months. 
I don't think the project needs any typescript.

But after this project, I was planning to work on an idea and build an app using NextJS (TypeScript) and Rust (rocket or actix).
Sounds interesting? Let me know i will ping as soon as i will start (~ in a week).
